// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSwc8NVHDnzjGVf2Vtnyn1v5vJsAfOPlQ',
    appId: '1:678146329560:web:6f3832c9a7dda125dbc0ad',
    messagingSenderId: '678146329560',
    projectId: 'smartcatcare',
    authDomain: 'smartcatcare.firebaseapp.com',
    databaseURL: 'https://smartcatcare-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartcatcare.firebasestorage.app',
    measurementId: 'G-TZVL1JDFTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4oEfPnlEYeFa8LlTyTacu5NMaYQhDC_A',
    appId: '1:678146329560:android:ad98ff0d303e1776dbc0ad',
    messagingSenderId: '678146329560',
    projectId: 'smartcatcare',
    databaseURL: 'https://smartcatcare-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartcatcare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnlmk5glK7DPxHXSUzVpHXmCQ_nmOHUCE',
    appId: '1:678146329560:ios:7d4d92ec6a6b2550dbc0ad',
    messagingSenderId: '678146329560',
    projectId: 'smartcatcare',
    databaseURL: 'https://smartcatcare-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartcatcare.firebasestorage.app',
    iosBundleId: 'com.example.smartpetcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnlmk5glK7DPxHXSUzVpHXmCQ_nmOHUCE',
    appId: '1:678146329560:ios:7d4d92ec6a6b2550dbc0ad',
    messagingSenderId: '678146329560',
    projectId: 'smartcatcare',
    databaseURL: 'https://smartcatcare-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartcatcare.firebasestorage.app',
    iosBundleId: 'com.example.smartpetcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSwc8NVHDnzjGVf2Vtnyn1v5vJsAfOPlQ',
    appId: '1:678146329560:web:269608d55f0d6641dbc0ad',
    messagingSenderId: '678146329560',
    projectId: 'smartcatcare',
    authDomain: 'smartcatcare.firebaseapp.com',
    databaseURL: 'https://smartcatcare-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartcatcare.firebasestorage.app',
    measurementId: 'G-VP8JCTPGFN',
  );
}
